### ISSUE TITLE
私有maven包引入不了啊

### ISSUE THREAD

**Issue by kennywgx** [deepexi/springcloud-exam#1]
我本地的/.m2无法找到optimus-commons包

**Comment by Mrcici** [comment]
引入不了加一

**Comment by kennywgx** [comment]
@Mrcici  我是把他的这个项目https://github.com/deepexi/optimus-commons拉下来本地打包的, 本地mvn打包报错但是我的本地mvn仓库却生成了对应的jar包。。。。什么鬼， 然后改为对应版本号就行了
